//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the FlatSharp FBS to C# compiler (source hash: 5.7.1.+0mrmo6wvGus45vgOUj9sDqF2Xr/Q6YWk7EBGTms6EM=)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using FlatSharp;
using FlatSharp.Attributes;
#pragma warning disable 0618
#nullable enable annotations
namespace A6
{
    [FlatBufferTableAttribute()]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class TextEntry
        : object
    {
        public TextEntry()
        {
            checked
            {
                this.OnInitialized(null);
            }
        }

#pragma warning disable CS8618
        protected TextEntry(FlatBufferDeserializationContext context)
        {
            checked
            {
            }
        }

#pragma warning restore CS8618
        public TextEntry(TextEntry source)
        {
            checked
            {
                this.OnInitialized(null);
            }
        }

        partial void OnInitialized(FlatBufferDeserializationContext? context);

        protected void OnFlatSharpDeserialized(FlatBufferDeserializationContext? context) => this.OnInitialized(context);

        [FlatBufferItemAttribute(0)]
        public virtual System.String name { get; set; }

        [FlatBufferItemAttribute(1)]
        public virtual System.String value { get; set; }

    }
    [FlatBufferTableAttribute()]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class DataEntry
        : object
    {
        public DataEntry()
        {
            checked
            {
                this.OnInitialized(null);
            }
        }

#pragma warning disable CS8618
        protected DataEntry(FlatBufferDeserializationContext context)
        {
            checked
            {
            }
        }

#pragma warning restore CS8618
        public DataEntry(DataEntry source)
        {
            checked
            {
                this.OnInitialized(null);
            }
        }

        partial void OnInitialized(FlatBufferDeserializationContext? context);

        protected void OnFlatSharpDeserialized(FlatBufferDeserializationContext? context) => this.OnInitialized(context);

        [FlatBufferItemAttribute(0)]
        public virtual System.String name { get; set; }

        [FlatBufferItemAttribute(1)]
        public virtual IList<System.Byte> value { get; set; }

    }
    [FlatBufferEnum(typeof(System.Byte))]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public enum Method : System.Byte
    {
        GET = (byte)(0),
        HEAD = (byte)(1),
        POST = (byte)(2),
        PUT = (byte)(3),
        DELETE = (byte)(4),
        MKCOL = (byte)(5),
        COPY = (byte)(6),
        MOVE = (byte)(7),
        OPTIONS = (byte)(8),
        PROPFIND = (byte)(9),
        PROPPATCH = (byte)(10),
        LOCK = (byte)(11),
        UNLOCK = (byte)(12),
        PATCH = (byte)(13),
        TRACE = (byte)(14),
    }

    namespace PrepareConf
    {
        [FlatBufferTableAttribute()]
        [System.Runtime.CompilerServices.CompilerGenerated]
        public partial class Req
            : object
        {
            public Req()
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

#pragma warning disable CS8618
            protected Req(FlatBufferDeserializationContext context)
            {
                checked
                {
                }
            }

#pragma warning restore CS8618
            public Req(Req source)
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

            partial void OnInitialized(FlatBufferDeserializationContext? context);

            protected void OnFlatSharpDeserialized(FlatBufferDeserializationContext? context) => this.OnInitialized(context);

            [FlatBufferItemAttribute(0)]
            public virtual IList<global::A6.TextEntry> conf { get; set; }

            [FlatBufferItemAttribute(1)]
            public virtual System.String key { get; set; }

        }
        [FlatBufferTableAttribute()]
        [System.Runtime.CompilerServices.CompilerGenerated]
        public partial class Resp
            : object
        {
            public Resp()
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

#pragma warning disable CS8618
            protected Resp(FlatBufferDeserializationContext context)
            {
                checked
                {
                }
            }

#pragma warning restore CS8618
            public Resp(Resp source)
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

            partial void OnInitialized(FlatBufferDeserializationContext? context);

            protected void OnFlatSharpDeserialized(FlatBufferDeserializationContext? context) => this.OnInitialized(context);

            [FlatBufferItemAttribute(0)]
            public virtual System.UInt32 conf_token { get; set; }

        }
    }
    namespace HTTPReqCall
    {
        [FlatBufferTableAttribute()]
        [System.Runtime.CompilerServices.CompilerGenerated]
        public partial class Req
            : object
        {
            public Req()
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

#pragma warning disable CS8618
            protected Req(FlatBufferDeserializationContext context)
            {

            }

#pragma warning restore CS8618
            public Req(Req source)
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

            partial void OnInitialized(FlatBufferDeserializationContext? context);

            protected void OnFlatSharpDeserialized(FlatBufferDeserializationContext? context) => this.OnInitialized(context);

            [FlatBufferItemAttribute(0)]
            public virtual System.UInt32 id { get; set; }

            [FlatBufferItemAttribute(1)]
            public virtual IList<System.Byte> src_ip { get; set; }

            [FlatBufferItemAttribute(2)]
            public virtual global::A6.Method method { get; set; }

            [FlatBufferItemAttribute(3)]
            public virtual System.String path { get; set; }

            [FlatBufferItemAttribute(4)]
            public virtual IList<global::A6.TextEntry> args { get; set; }

            [FlatBufferItemAttribute(5)]
            public virtual IList<global::A6.TextEntry> headers { get; set; }

            [FlatBufferItemAttribute(6)]
            public virtual System.UInt32 conf_token { get; set; }

        }
        [FlatBufferTableAttribute()]
        [System.Runtime.CompilerServices.CompilerGenerated]
        public partial class Stop
            : object
        {
            public Stop()
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

#pragma warning disable CS8618
            protected Stop(FlatBufferDeserializationContext context)
            {
                checked
                {
                }
            }

#pragma warning restore CS8618
            public Stop(Stop source)
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

            partial void OnInitialized(FlatBufferDeserializationContext? context);

            protected void OnFlatSharpDeserialized(FlatBufferDeserializationContext? context) => this.OnInitialized(context);

            [FlatBufferItemAttribute(0)]
            public virtual System.UInt16 status { get; set; }

            [FlatBufferItemAttribute(1)]
            public virtual IList<global::A6.TextEntry> headers { get; set; }

            [FlatBufferItemAttribute(2)]
            public virtual IList<System.Byte> body { get; set; }

        }
        [FlatBufferTableAttribute()]
        [System.Runtime.CompilerServices.CompilerGenerated]
        public partial class Rewrite
            : object
        {
            public Rewrite()
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

#pragma warning disable CS8618
            protected Rewrite(FlatBufferDeserializationContext context)
            {
                checked
                {
                }
            }

#pragma warning restore CS8618
            public Rewrite(Rewrite source)
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

            partial void OnInitialized(FlatBufferDeserializationContext? context);

            protected void OnFlatSharpDeserialized(FlatBufferDeserializationContext? context) => this.OnInitialized(context);

            [FlatBufferItemAttribute(0)]
            public virtual System.String path { get; set; }

            [FlatBufferItemAttribute(1)]
            public virtual IList<global::A6.TextEntry> headers { get; set; }

            [FlatBufferItemAttribute(2)]
            public virtual IList<global::A6.TextEntry> args { get; set; }

        }
        [System.Runtime.CompilerServices.CompilerGenerated]
        public partial class A6Action : FlatBufferUnion<global::A6.HTTPReqCall.Stop, global::A6.HTTPReqCall.Rewrite>
        {
            public enum ItemKind : byte
            {
                Stop = 1,
                Rewrite = 2,
            }


            public ItemKind Kind => (ItemKind)base.Discriminator;

            public A6Action(global::A6.HTTPReqCall.Stop value) : base(value)
            {
                checked
                { }
            }

            public global::A6.HTTPReqCall.Stop Stop => base.Item1;

            public A6Action(global::A6.HTTPReqCall.Rewrite value) : base(value)
            {
                checked
                { }
            }

            public global::A6.HTTPReqCall.Rewrite Rewrite => base.Item2;
            public new TReturn Switch<TState, TReturn>(
                TState state,
                Func<TState, TReturn> caseDefault
                , Func<TState, global::A6.HTTPReqCall.Stop, TReturn> caseStop
                , Func<TState, global::A6.HTTPReqCall.Rewrite, TReturn> caseRewrite
            ) => base.Switch<TState, TReturn>(state, caseDefault, caseStop, caseRewrite);
            public new TReturn Switch<TReturn>(
                Func<TReturn> caseDefault
                , Func<global::A6.HTTPReqCall.Stop, TReturn> caseStop
                , Func<global::A6.HTTPReqCall.Rewrite, TReturn> caseRewrite
            ) => base.Switch<TReturn>(caseDefault, caseStop, caseRewrite);
            public new void Switch<TState>(
                TState state,
                Action<TState> caseDefault
                , Action<TState, global::A6.HTTPReqCall.Stop> caseStop
                , Action<TState, global::A6.HTTPReqCall.Rewrite> caseRewrite
            ) => base.Switch<TState>(state, caseDefault, caseStop, caseRewrite);
            public  void Switch(
                Action caseDefault
                , Action<global::A6.HTTPReqCall.Stop> caseStop
                , Action<global::A6.HTTPReqCall.Rewrite> caseRewrite
            ) => base.Switch(caseDefault, caseStop, caseRewrite);
        }

        [FlatBufferTableAttribute()]
        [System.Runtime.CompilerServices.CompilerGenerated]
        public partial class Resp
            : object
        {
            public Resp()
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

#pragma warning disable CS8618
            protected Resp(FlatBufferDeserializationContext context)
            {
                checked
                {
                }
            }

#pragma warning restore CS8618
            public Resp(Resp source)
            {
                checked
                {
                    this.OnInitialized(null);
                }
            }

            partial void OnInitialized(FlatBufferDeserializationContext? context);

            protected void OnFlatSharpDeserialized(FlatBufferDeserializationContext? context) => this.OnInitialized(context);

            [FlatBufferItemAttribute(0)]
            public virtual System.UInt32 id { get; set; }

            [FlatBufferItemAttribute(1)]
            public virtual global::A6.HTTPReqCall.A6Action action { get; set; }

        }
    }
}
#nullable restore
#pragma warning restore 0618
